### ISSUE TITLE
Z-index customization

### ISSUE THREAD

**Issue by djcaesar9114** [Daniel-Knights/vue-dk-toast#10]
Hello,
It would be great to customize z-index, as I have some elements overlaying the toasts.
Thanks for the work.

**Comment by Daniel-Knights** [comment]
Hey @djcaesar9114, I did set the `z-index` of the container at `10000` to give some leeway over how you set other elements. Are they 3rd party elements you can't change?

**Comment by djcaesar9114** [comment]
Sorry for the late of my reply, I didn't see your message...
I can change everything in my app, but I think it could be an interesting feature to be able to configure the z-index.

**Comment by Daniel-Knights** [comment]
This seems like an unnecessary feature tbh. If it's absolutely necessary to change the z-index, just target the container class
