### ISSUE TITLE
Typescript import error

### ISSUE THREAD

**Issue by ErikZakrisson** [Daniel-Knights/vue-dk-toast#15]
Really liking this lightweight library, just what I need.
I have a problem with Typescript and Vue3 though. My compiler gives the following error:
`Error: src/main.ts(11,9): error TS2345: Argument of type 'import().Plugin' is not assignable to parameter of type 'import().Plugin'.`

This is when importing the library: `app.use(DKToast)`

Changing the declaration of DKToast to use Plugin_2 instead of Plugin takes care of the problem. Not sure why since Plugin_2 is exported as Plugin in Vue. Any ideas?

**Comment by Daniel-Knights** [comment]
Hi, thanks Erik. I'll look into this soon as I can 👍

**Comment by Daniel-Knights** [comment]
I can't reproduce this error. Could you post any more details?

**Comment by ErikZakrisson** [comment]
Yeah, this is weird, must be something on my end. It works when my colleague is pushing changes. Only difference is that he is on a Mac and I'm using Ubuntu. Both have Vue 3.2.20 and TS 4.4.4. Don't really understand why but it has most likely nothing to do with this lib. I guess we can close this issue.
