### ISSUE TITLE
Uncaught (in promise) DOMException: String contains an invalid character

### ISSUE THREAD

**Issue by CoreyVincent** [Daniel-Knights/vue-dk-toast#16]
I'm using Tailwindcss. I was trying to add more than one class to the "class" property in `toast()`. 
I get the error:
`Uncaught (in promise) DOMException: String contains an invalid character    dkToast.umd.min.js:191:377`

Here's my code:
```ts
const toast = inject('$toast')
toast('simple', {
  duration: false,
  positionY: 'top',
  positionX: 'right',
  disableClick: false,
  class: 'bg-gray-100 border-2 border-gray-200 text-gray-800 p-4 rounded-sm shadow-md',
  max: 6,
})
```
Getting rid of the spaces resolves the issue, but doesn't allow me to have more than one class.
Am I using this property in the wrong way?

**Comment by CoreyVincent** [comment]
I also tried just setting:
```ts
  class: 'bg-blue-800',
```
And it doesn't seem to change the components style, still just white.

**Comment by Daniel-Knights** [comment]
Good spot. Not your mistake, it uses `classList.add` which doesn't allow whitespace. I'll look into this when I have some spare time. Thanks for opening an issue

**Comment by Daniel-Knights** [comment]
You can now pass an array of classes to any `class` option

**Comment by CoreyVincent** [comment]
Thanks for the quick response and fix!
