### ISSUE TITLE
Features I would like to have in vue-dk-toast

### ISSUE THREAD

**Issue by sergeynilov** [Daniel-Knights/vue-dk-toast#3]
1) Looking how vue-dk-toast works I see that 
styles.color/backgroundColor do not work locally, but only globally(in src/main.js), when 
toast is set for app object. Could you please tro make these options locally?
2) Can you please implement title( apart from text)?
3) Can you please implement custom html for text and title?
Thanks in advance!

**Comment by Daniel-Knights** [comment]
Hi, @sergeynilov, `color` and `backgroundColor` both work locally, maybe you're setting them wrong? As for the other two suggestions, they're worth thinking about but the aim is for `vue-dk-toast` to be simple and I think having separate title and HTML options would over-complicate it

**Comment by 9mm** [comment]
@Daniel-Knights at the very least it might be nice to have message simply accept a component. Multi-line toasts are pretty common from what I've seen... so perhaps instead of a separate title you simply allow custom HTML in the toast?

**Comment by Daniel-Knights** [comment]
@9mm `slotLeft` and `slotRight` accept custom HTML and default to being centre-aligned if no text is passed, so it's essentially the same thing

**Comment by 9mm** [comment]
Mm I see, although the height of the toast is fixed via css and doesn't grow with the contents (or rather, however tall the left/right is)

**Comment by 9mm** [comment]
Ah bizarre, it seems to work if I wrap everything in a div (because of flexbox I assume). I originally only tried a `<br>`

**Comment by Daniel-Knights** [comment]
If text is passed, the slots are set to `position: absolute` in which case the height wouldn't grow with the contents. But, you could just leave out the text entirely and pass only raw HTML. Just be careful of XSS attacks if the user has control over what goes inside

**Comment by 9mm** [comment]
I gotcha, that makes sense. I used text the first time i tried... cool deal, thanks
