### ISSUE TITLE
Implementation in separate typescript file

### ISSUE THREAD

**Issue by chielvanieperen** [Daniel-Knights/vue-dk-toast#4]
Hi there,

Really liking this plugin. Was just wondering how I can get it to work in a separate typescript file.

I am very new to Vue, and I followed the instructions: https://github.com/Daniel-Knights/vue-dk-toast#typescript-support

But my file doesn't recognise the `setup()` function and `const toast` is undefined.

Would really appreciate it if I knew how to get it to run in a separate file. The idea is to make 2 functions with 2 toasts and a message parameter. Because I want a succes toast, and error toast that can be used in multiple places :) Or maybe add a parameter to pass a class to the HTML element?

**Comment by Daniel-Knights** [comment]
Thanks @chvidev,  glad you like it. `setup` is a standard Vue method which goes inside component definitions. Is this how you have it set?

Feel free to post any code if it helps

**Comment by chielvanieperen** [comment]
Thanks for your quick reply @Daniel-Knights .

I included the code I have now, it's not working but I hope you can get the idea of what I want from this. Inside a component, I call: `import Utils from '@/services/global-utils';`. Then I want to use `Utils.successToast('Something here')` in various components in the application.
[test.ts.zip](https://github.com/Daniel-Knights/vue-dk-toast/files/5928190/test.ts.zip)

**Comment by Daniel-Knights** [comment]
`setup` doesn't do anything by itself, it needs to be part of a Vue component. For example:

```ts
<template>
    ...
</template>

<script lang="ts">
import { defineComponent, inject } from 'vue'
import type { Toast } from 'vue-dk-toast'

export default defineComponent({
    name: 'App',
    setup() {
        const toast = inject<Toast>('$toast')

        function successToast(msg: string): void {
            if (toast) toast(msg)
        }

        return { successToast }
    }
})
</script>
```

So, to have a separate file which serves as a wrapper for the toast you can define the wrapper function:

```ts
import { inject } from 'vue'
import type { Toast } from 'vue-dk-toast'

function successToast(message: string): void {
    const toast = inject<Toast>('$toast')

    if (toast) toast(message, successConfig)
}

const successConfig = {
    duration: 2000,
    styles: {
        borderRadius: '25px',
        backgroundColor: 'green'
    }
}

export default { successToast }
```

Then, anywhere you want to use it:

```ts
<script lang="ts">
import { defineComponent } from 'vue'
import Utils from './test'

export default defineComponent({
    // ...
    setup() {
        Utils.successToast('Simple!')
    }
    // ...
})
</script>
```

**Comment by chielvanieperen** [comment]
Thank you so much. I will try this as soon as I can and let you know if it worked.

**Comment by chielvanieperen** [comment]
Hi @Daniel-Knights I can now access the scope, that's good. But when I call the function it will give me a warning:
`runtime-core.esm-bundler.js?5c40:38 [Vue warn]: inject() can only be used inside setup() or functional components`

And `inject` is undefined in the file. It there a way around this?

***Edit**: I got it to work, thank you for the help @Daniel-Knights

**Comment by Daniel-Knights** [comment]
No problem, @chvidev.

For anyone else who might read this, it would be useful to add a `this` argument so you can access it inside templates:

```ts
import { ComponentPublicInstance, inject } from 'vue'
import type { Toast } from './lib/toast.d'

function successToast(message: string, thisArg?: ComponentPublicInstance): void {
    if (thisArg) thisArg.$toast('Simple!', successConfig)
    else {
        const toast = inject<Toast>('$toast')

        if (toast) toast(message, successConfig)
    }
}

const successConfig = {
    duration: 2000,
    styles: {
        borderRadius: '25px',
        backgroundColor: 'green'
    }
}

export default { successToast }
```

```vue
<template>
    <button @click="Utils.successToast('Simple!', this)" id="create-toast">
        Create Toast
    </button>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Utils from './test'

export default defineComponent({
    setup() {
        return { Utils }
    },
})
```
