### ISSUE TITLE
Align toast in center

### ISSUE THREAD

**Issue by djcaesar9114** [Daniel-Knights/vue-dk-toast#5]
It would be great to align the toast at the center (at least horizontally).

**Comment by Daniel-Knights** [comment]
This is a good idea, I'll see about adding this when I get a chance 👍

**Comment by Daniel-Knights** [comment]
Thanks for suggesting this, I've added the option [here](https://github.com/Daniel-Knights/vue-dk-toast/commit/99a7e5c292542a5b747e0439b3ec3f7b69cc3453).

**Comment by djcaesar9114** [comment]
Very fast... I knew I chose the good toast! Great job, BTW.
