### ISSUE TITLE
position can't be set locally

### ISSUE THREAD

**Issue by djcaesar9114** [Daniel-Knights/vue-dk-toast#6]
I don't know if it's a bug or on purpose, but when I set "positionX: 'center'" locally, it doesn't work, I have to set it when I "use" DJToast in the main.js file.
It could be great to be able to change the position of the toast locally. 
Maybe using a wrapper with flex and changing the flex property when called locally could do the trick.

**Comment by Daniel-Knights** [comment]
This is on my todo list atm so it will be coming soon. Each toast is added to a single parent container so the only tricky thing here will be conflicting containers, especially on small screen sizes. Need to think this one through a bit before implementing it.

**Comment by Daniel-Knights** [comment]
This has been implemented as of V2
