### ISSUE TITLE
toast position on mobile

### ISSUE THREAD

**Issue by noxz-dev** [Daniel-Knights/vue-dk-toast#8]
Hi, is it possible to change the position of the toast on mobile ?

**Comment by Daniel-Knights** [comment]
Hey @HeyImNoxz, I can add this feature when I have time. Thanks for pointing this out 👍

**Comment by noxz-dev** [comment]
Thx

**Comment by Daniel-Knights** [comment]
Added with [v2.2.0](https://github.com/Daniel-Knights/vue-dk-toast/commit/18f99f6326d6dd128e6c3593b33a5b7e41633a16)
