### ISSUE TITLE
dk__toast-container z-index

### ISSUE THREAD

**Issue by jensengbg-christian-mosciatti** [Daniel-Knights/vue-dk-toast#9]
Hi

first of all: Really nice libriary!

then: is it possible to change z-index of dk__toast-container class to a higher value? Having a Modal the toast message pop-ups in the background.

Many thanks :)

**Comment by Daniel-Knights** [comment]
Hey, thanks @jensengbg-christian-mosciatti.

Good point, I hadn't thought of that. Added in [v2.2.1](https://github.com/Daniel-Knights/vue-dk-toast/commit/67783007171f6ccedac9fe9671cc3b66f659d233) 👍
